---
- name: Prepare Proxmox host and create VM template
  hosts: proxmox
  gather_facts: yes
  become: yes

  roles:
    - role: proxmox_host
      tags: 
        - bootstrap
        - proxmox_host               # Prepares Proxmox (Debian, network, LVM, packages)
    - role: proxmox_terraform_access
      tags: 
        - bootstrap
        - proxmox_terraform_access   # Creates service user and API token for Terraform
    - role: proxmox_vm_template
      tags:
        - bootstrap
        - proxmox_vm_template        # Builds golden vm template for cloning via Terraform 