# ---------------------------
# Kubespray Inventory Template
# ---------------------------

[all]
k8s-control-1 ansible_host=172.16.16.21
k8s-control-2 ansible_host=172.16.16.22
k8s-control-3 ansible_host=172.16.16.23
k8s-node-1 ansible_host=172.16.16.31
k8s-node-2 ansible_host=172.16.16.32
k8s-node-3 ansible_host=172.16.16.33

[kube_control_plane]
k8s-control-1 ansible_host=172.16.16.21
k8s-control-2 ansible_host=172.16.16.22
k8s-control-3 ansible_host=172.16.16.23

[etcd]
k8s-control-1 ansible_host=172.16.16.21
k8s-control-2 ansible_host=172.16.16.22
k8s-control-3 ansible_host=172.16.16.23

[kube_node]
k8s-node-1 ansible_host=172.16.16.31
k8s-node-2 ansible_host=172.16.16.32
k8s-node-3 ansible_host=172.16.16.33

[k8s_cluster:children]
kube_control_plane
kube_node

[all:vars]
ansible_user=ubuntu
ansible_become=true
ansible_ssh_common_args='-o ProxyJump=kube-lab -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
ansible_ssh_private_key_file=/root/.ssh/id_rsa