- name: Perform dist-upgrade
  ansible.builtin.apt:
    upgrade: dist
    update_cache: yes

- name: Add Proxmox GPG key
  ansible.builtin.get_url:
    url: http://download.proxmox.com/debian/proxmox-release-bookworm.gpg
    dest: /etc/apt/trusted.gpg.d/proxmox-release.gpg
    mode: '0644'

- name: Add Proxmox APT repository
  ansible.builtin.apt_repository:
    repo: "deb http://download.proxmox.com/debian/pve bookworm pve-no-subscription"
    filename: "pve-install"
    state: present

- name: Install Proxmox VE
  apt:
    name: proxmox-ve
    state: present
    update_cache: yes

- name: Remove Proxmox enterprise repo (created by proxmox-ve)
  file:
    path: /etc/apt/sources.list.d/pve-enterprise.list
    state: absent

- name: Reboot
  ansible.builtin.reboot:
    msg: "Reboot initiated by Ansible"
    connect_timeout: 5
    reboot_timeout: 600